
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_a1
     - joint_a2
     - joint_a3
     - joint_a4
     - joint_a5
     - joint_a6
     - joint_a7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_a1: {trajectory: 0.1, goal: 0.1}
      joint_a2: {trajectory: 0.1, goal: 0.1}
      joint_a3: {trajectory: 0.1, goal: 0.1}
      joint_a4: {trajectory: 0.1, goal: 0.1}
      joint_a5: {trajectory: 0.1, goal: 0.1}
      joint_a6: {trajectory: 0.1, goal: 0.1}
      joint_a7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  # gains:
  #   ur10shoulder_pan_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10shoulder_lift_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10elbow_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10wrist_1_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10wrist_2_joint: {p: 10,  d: 1, i: 1, i_clamp: 1}
  #   ur10wrist_3_joint:  {p: 10,  d: 1, i: 1, i_clamp: 1}
# gazebo_ros_control: 
#   pid_gains:
#     ur10shoulder_pan_joint: {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10shoulder_lift_joint: {p: 100, d: 0, i: 10.0, i_clamp: 50}
#     ur10elbow_joint:  {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10wrist_1_joint:  {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10wrist_2_joint:  {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
#     ur10wrist_3_joint:   {p: 100.0,  i: 0.01, d: 10.0, i_clamp: 1}
